<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
    <div class="product-view product-info">
    
        <div class="product-essential row">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            
            <div class="col-lg-5 col-md-6 col-sm-12 col-xs-12 image-container product-img-box">
                <?php echo $this->getChildHtml('media') ?>
            </div>
            <div class="col-lg-7 col-md-6 col-sm-12 col-xs-12 product-shop product-view">
                 <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
               

                <?php if ($this->canEmailToFriend()): ?>
                    <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
                <?php endif; ?>
                <div class="review"> <?php echo $this->getReviewsSummaryHtml($_product, false, true)?> </div>

                <div class="share"> </div>

                <div itemtype="http://schema.org/Offer" itemscope="" class="price"> 
                    <?php echo $this->getChildHtml('alert_urls') ?>
                    <?php echo $this->getChildHtml('product_type_data') ?>
                    <?php echo $this->getTierPriceHtml() ?>
                    <?php echo $this->getChildHtml('extrahint') ?>
                </div>


                <div class="product-extra">

                 
                </div>

                <div class="description"> 
                    <?php if ($_product->getShortDescription()):?>
                    <div class="short-description">
                        <h2><?php echo $this->__('Quick Overview') ?></h2>
                        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                    </div>
                <?php endif;?>

                <?php echo $this->getChildHtml('other');?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>
                
                 <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>
                </div>


                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>                                
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$_product->isSaleable()): ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>

                
            </div>
           

        </form>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
       
    </div>
</div>
    <?php echo $this->getChildHtml('info_tabs') ?>
    <div class="tabs-group block row-fuild product-collateral">
       <div id="tabs" class="htabs col-lg-3 col-md-3 col-sm-3 col-xs-12"> 
            <ul class="nav nav-tabs clearfix">

             
            <?php
             $tmp_html = "";
            ?>
            <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html){
                $tmp_html .= "<div id=\"tab-{$alias}\" class=\"tab-content block-{$alias}\">";
                $tmp_html .= $html;
                $tmp_html .= '<br class="clear clr"/>';
                $tmp_html .= "</div>";
                if ($title = $this->getChildData($alias, 'title')){
                    echo '<li> <a href="#tab-'.$alias.'">'.$this->escapeHtml($title).'</a> </li>';
                }else{
                    echo '<li> <a href="#tab-'.$alias.'">'.$this->escapeHtml(ucfirst($alias)).'</a> </li>';
                }
             };?>
            <?php
                $route = Mage::app()->getRequest()->getRouteName();
            ?>
            <?php if($route != "review" && $route !="tempcp") { ?>
                 <?php if($product_additional_data = $this->getChildHtml('product_additional_data')): ?>
                     <li><a href="#tab-tags"><?php echo Mage::helper('ves_tempcp')->__("Product Tags");?></a> </li>
                       <?php $product_additional_data = '<div id="tab-tags" class="tab-content">'.$product_additional_data.'<br class="clear clr"/></div>'; ?>
                    <?php endif; ?>
            <?php } ?>

            <?php 
                $product_customtab = "";
                if($themeConfig->get("enable_product_customtab", 0)){ 
                    echo '<li> <a href="#tab-custom">'.$themeConfig->get("product_customtab_name","").'</a> </li>';
                    $product_customtab = "<div id=\"tab-custom\" class=\"tab-content box-custom\">";
                    $product_customtab .= $themeConfig->get("product_customtab_content","",true);
                    $product_customtab .= '<br class="clear clr"/>';
                    $product_customtab .= '</div>';
                } ?>
            <?php if($route != "review" && $route !="tempcp") { ?>
            <li> <a href="#tab-reviews"><?php echo Mage::helper('ves_tempcp')->__("Reviews");?></a> </li>
            <?php } ?>

            </ul> 

        </div>


        <div class="tab-content col-lg-9 col-md-9 col-sm-9 col-xs-12"> 
         <?php echo $tmp_html; ?>
        
        <?php echo $product_additional_data; ?>
        <?php echo $product_customtab; ?>
        <?php if($route != "review" && $route !="tempcp") { ?>
        <div id="tab-reviews">
            <?php echo $this->getChildHtml("review_tab"); ?>
        </div>
        <?php } else { ?>

        <?php echo $this->getChildHtml('product_additional_data'); ?>

        <?php } ?>
    </div>
 </div>

<?php echo $this->getChildHtml('upsell_products') ?>
<?php echo $this->getChildHtml('related_products') ?>
<script type="text/javascript">
jQuery('#tabs a').tabs();
</script> 