<?php 

?>
<section class="padding-top-50  padding-bottom-50">
	<div class="container">		
		<div class="col-sm-2">			
		</div>
		<div class="col-sm-8 align-center">
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
			<p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
	    </div>
		<div class="col-sm-2">			
		</div>
	</div>
</section>
<section class="padding-top-50 padding-bottom-100" style="background-image:url('<?php echo $this->getSkinUrl() ?>images/3rdsection.jpg');background-size:100% 100%;background-repeat:no-repeat">
	<div class="container">		
		<div class="col-sm-2">			
		</div>
		<div class="col-sm-8 align-center">
			<h1 class="color-white" style="font-size:20px;margin-bottom:10px">Book your Demo today, for the perfect cup of filter coffee</h1>
			<h1 class="color-white" style="font-size:40px;text-transform:uppercase;">On the demo day you will Experience</h1>			
	    </div>
		<div class="col-sm-2">			
		</div>
	</div>
</section>
<section class="padding-top-50 padding-bottom-50">
	<div class="container">		
		<div class="col-sm-1">			
		</div>
		<div class="col-sm-10 align-center">
			<div class="col-sm-4">		
				<img src="<?php echo $this->getSkinUrl() ?>images/drink-profile.png"></br></br>
				<h2 class="color-brown" style="font-size:20px;text-transform:uppercase">Drink Profiling</h2></br>
				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
			</div>
			<div class="col-sm-4">		
				<img src="<?php echo $this->getSkinUrl() ?>images/machine-setup.png"></br></br>
				<h2 class="color-brown" style="font-size:20px;text-transform:uppercase">Drink Profiling</h2></br>
				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
			</div>
			<div class="col-sm-4">		
				<img src="<?php echo $this->getSkinUrl() ?>images/helpfull-advice.png"></br></br>
				<h2 class="color-brown" style="font-size:20px;text-transform:uppercase">Drink Profiling</h2></br>
				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
			</div>
			<h1 class="color-white" style="font-size:20px;margin-bottom:10px">Book your Demo today, for the perfect cup of filter coffee</h1>
			<h1 class="color-white" style="font-size:40px;text-transform:uppercase;">On the demo day you will Experience</h1>			
	    </div>
		<div class="col-sm-1">			
		</div>
	</div>
</section>
<section class="padding-top-50 padding-bottom-80" style="background-color:#e6e7e8">
	<div class="container">		
		<div class="col-sm-2">			
		</div>
		<div class="col-sm-8 align-center">
			<h1 class="color-ash" style="font-size:20px;margin-bottom:10px;text-transform:uppercase;">Book your</h1>
			<h1 class="color-brown" style="font-size:40px;text-transform:uppercase;">Coffee Tasting</h1></br>
			<p class="font-size-15">Fill in your details below and one of our team will call you to make arrangement</p>
	    </div>
		<div class="col-sm-2">			
		</div>
	</div>
</section>
<section class="margin-top-50 padding-top-30 padding-bottom-30">
	<div class="col-sm-6 padding-0">
		<img src="<?php echo $this->getSkinUrl() ?>/images/contact-section.jpg" style="width:100%">
	</div>		
	<div class="col-sm-6">
		<div class="col-sm-9 corporate-form" style="margin: auto;float: none;">
			<form name="test-form" id="my-custom-form" action="" method="post">
			<input type="text" name="name" placeholder="Name" class="input-text required-entry"/>
			<input type="text" name="company" placeholder="Company" class="input-text required-entry"/>
			<input type="text" name="email" id="useremail" placeholder="Email" class="input-text required-entry"/>
			<input type="text" name="phone" id="validate-number" placeholder="Phone" class="input-text required-entry"/>
			<input type="text" name="employee" id="validate-number" placeholder="No.of Employees" class="input-text required-entry"/>			
			<input type="submit" name="Send"/>
			</form>
		</div>
	</div>
</section>
<script type="text/javascript">
    //< ![CDATA[
        var customForm = new VarienForm('my-custom-form');
    //]]>
</script>