<?php 

?>
<section id="ves-masstop2" class="ves-masstop2" style="background-image:url('images/coffee-bean.png')">
	<div class="container">
		<center><h1 CLASS="welcometext roast" style="text-transform:capitalize;">Some of Our Customers who love our coffee</h1></center>
		<div class="col-sm-2">			
		</div>
		<div class="col-sm-9">
			<div class="owl-carousel owl-theme">
				<div> <img src="<?php echo $this->getSkinUrl() ?>/images/clients/1.jpg"></div>
				<div> <img src="<?php echo $this->getSkinUrl() ?>/images/clients/2.jpg"></div>
				<div> <img src="<?php echo $this->getSkinUrl() ?>/images/clients/3.jpg"></div>
				<div> <img src="<?php echo $this->getSkinUrl() ?>/images/clients/4.jpg"></div>
				<div> <img src="<?php echo $this->getSkinUrl() ?>/images/clients/5.jpg"></div>
				<div> <img src="<?php echo $this->getSkinUrl() ?>/images/clients/6.jpg"></div>
			</div>
	    </div>
		<div class="col-sm-2">			
		</div>
	</div>
</section>
<script>
	jQuery(document).ready(function(){
	 jQuery('.owl-carousel').owlCarousel();
	});
</script>
