<?php 

?>
<section id="ves-masstop2" class="ves-masstop2" style="background-color:#f1f2f2;    float: left;">
	<div class="container">
		<div class="col-sm-2">
			<h1 class="welcometext feature">Featured On</h1>
		</div>
		<div class="col-sm-10">
			<img src="<?php echo $this->getSkinUrl() ?>/images/featured-on/1.jpg">
			<img src="<?php echo $this->getSkinUrl() ?>/images/featured-on/2.jpg">
			<img src="<?php echo $this->getSkinUrl() ?>/images/featured-on/3.jpg">
			<img src="<?php echo $this->getSkinUrl() ?>/images/featured-on/4.jpg">
			<img src="<?php echo $this->getSkinUrl() ?>/images/featured-on/5.jpg">
		</div>
		
	   
	</div>
</section>
