<?php 

?>
<section class="padding-top-50  padding-bottom-50">
	<div class="container">		
		<div class="col-sm-2">			
		</div>
		<div class="col-sm-8">
			<p style="text-align:left;margin-bottom:0px;"class="welcomecontent coffeecontent">We produce Robusta and Arabica beans, grown at 2500 - 5000 feet above sea level, handpicked and sorted. We're kind of outdoorsy in our approach, because to produce the right beans, you have to tromp through some pretty rugged interior locations of Coorg and other coffee growing regions of Karnataka.</p> 
			<p style="text-align:left;margin-bottom:20px;"class="welcomecontent coffeecontent">What we do isn’t just cultivation and manufacturing, it’s an Art….Every step of the way, from coffee cherry to your cup, is managed to fit our exacting standards. </p>
			<p style="text-align:left;" class="welcomecontent coffeecontent">It’s possible that in a massive roasting, that a bean with too much time in the roaster can lose its sensitive undertones, or be so overwhelming that the refined nature of the bean is lost forever. Not so though with Aromas of Coorg</p>
			
	    </div>
	</div>
</section>
<section class="padding-top-100 padding-bottom-100" style="background-image:url('<?php echo $this->getSkinUrl() ?>images/3rdsection.jpg');background-size:100% 100%;background-repeat:no-repeat">
	<div class="container">		
		<div class="col-sm-2">			
		</div>
		<div class="col-sm-8 align-center">
			<h1 class="color-white align-center" style="font-size:30px;line-height:50px;">Our approach is simple:</h1>
			<h1 class="color-white align-center" style="font-size:30px;line-height:50px;">The best beans, artfully roasted,</h1>
			<h1 class="color-white align-center" style="font-size:30px;line-height:50px;">Then we call it great.</h1>				
	    </div>
		<div class="col-sm-2">			
		</div>
	</div>
</section>
<section class="padding-top-50  padding-bottom-30">
	<div class="container">		
		<div class="col-sm-2">			
		</div>
		<div class="col-sm-8 align-center">
			<p class="welcomecontent coffeecontent" style="text-align:left;margin-bottom:20px;">We craft roast only limited quantities, our Coffee is roasted using sensors that will track temperature shifts as fine as 1 degree. That slight variance can make all the difference between a coffee that  is soothing and owns a pleasurable complex flavor and one that is overwhelming and indiscernible. Yet the art of the roasting process is preserved, as every batch is monitored by hand, eye, ear and nose, using the senses along with the technology to deliver the perfect bean and a great cup of coffee for you</p>
			<p class="welcomecontent coffeecontent"style="text-align:left;">Every cup of "Aromas of Coorg" coffee reflects our tradition, taste, expertise and quality</p>
	    	</div>
		<div class="col-sm-2">			
		</div>
	</div>
</section>

<section class="padding-bottom-20">
	<div class="container">		
		<div class="col-sm-2">			
		</div>
		<div class="col-sm-8 align-center">
			<h1 class="welcometext" style="font-size:30px;line-height:50px;color:#40281e;">PLACE YOUR ORDER NOW AND COMPLETE THE <br /> EXPERIENCE !!!</h1>
	    </div>
		<div class="col-sm-2">			
		</div>
	</div>
</section>
<section class="padding-top-30  padding-bottom-20">
	<div class="container">		
		<div class="col-sm-3">			
		</div>
		<div class="col-sm-3 align-center backgroundimage">
		<img src="<?php echo $this->getSkinUrl() ?>images/coffee-for-home.png">
		<p class="image1 align-center">Coffee for Home</p>
		</div>
		<div class="col-sm-3 align-center backgroundimage">
		<img src="<?php echo $this->getSkinUrl() ?>images/coffee-for-office.png">
		<p class="image1 align-center">Coffee for Office</p>
		</div>
		<div class="col-sm-3">
		</div>
	</div>
</section>
