<?php 

?>
<section id="ves-masstop2" class="ves-masstop2" style="background-image:url('<?php echo $this->getSkinUrl() ?>/images/coffee-bean.png');padding-top: 50px;padding-bottom: 120px;background-repeat: no-repeat;
    background-position: right 157%;">
	<div class="container">
		<div class="col-sm-3 ">
			<img src="<?php echo $this->getSkinUrl() ?>/images/coffee-cup.png">
		</div>
		<div class="col-sm-7">
			<center>
				<h1 class="welcometext">Welcome to the Brew House of your next cup of filter coffee</h1>
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('welcome')->toHtml() ?>
			</center>
		</div>
		<div class="col-sm-2">
			
		</div>
	   
	</div>
</section>
