<?php 
$_product = $this->getProduct();
// Get the Discount
if($_product->getSpecialPrice()):
	$save_price = (float)$_product->getPrice() - (float)$_product->getSpecialPrice();
	$discount = round(($save_price/$_product->getPrice())*100);
	$date1 = date('G:i:s', strtotime($_product->getSpecialToDate()));
	if ($date1 == "0:00:00") {
	    $targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($_product->getSpecialToDate()));
	}else{
	    $targetDate = date('m/d/Y G:i:s', strtotime($_product->getSpecialToDate()));
	}
?>
	<div class="block block-deal-info" style="clear:both">
		<div class="block-title">
			<strong><span><?php echo $this->__("Time Left To Buy");?></span></strong>
		</div>
		<div class="block-content">
				<div id="item_countdown_<?php echo $_product->getId(); ?>" class="item-countdown"></div>
				<script type="text/javascript">
		            jQuery(document).ready(function($){
		                    $("#item_countdown_<?php echo $_product->getId(); ?>").lofCountDown({
		                        formatStyle:2,
		                        TargetDate:"<?php echo $targetDate; ?>",
		                        DisplayFormat:"<ul><li><div><?php echo $this->__('Day');?></div>%%D%% </li><li><div><?php echo $this->__('Hours');?></div> %%H%% </li><li><div><?php echo $this->__('Mins');?></div> %%M%% </li><li><div><?php echo $this->__('Secs');?></div> %%S%% </li></ul>",
		                        FinishMessage:"<?php echo $this->__('Expired');?>",
		                    });
		                });
		        </script>
			<div class="clear" style="clear:both"></div>
			<?php $today = Mage::getModel('core/date')->date('m/d/Y G:i:s');
            if($targetDate > $today){
            ?>
			<div class="deal_detail">
	            <ul>
	                <li>
	                    <span><?php echo $this->__("Discount");?></span>
	                    <span class="deal_detail_num"><?php echo $discount;?>%</span>
	                </li>
	                <li>
	                    <span><?php echo $this->__("You save");?></span>
	                    <span class="deal_detail_num"><span class="price">$<?php echo $save_price; ?></span></span>
	                </li>
	                <li>
	                    <span><?php echo $this->__("Bought");?></span>
	                    <span class="deal_detail_num"><?php echo Mage::helper("ves_tempcp")->getBought($_product->getSku());?></span>
	                </li>
	            </ul>
	        </div>
	       	<?php } //check time live ?>
		</div>
	</div>
<?php endif; ?>