<div >
<form method="post" action="<?php echo $this->getUrl('coffee-subscription/index/checkout'); ?>" name="custom_checkout" id="sub_checkout">
<?php 
$subscription_request = Mage::getSingleton('core/session')->getSubscriptionRequest();

?>
<div class="coffee-sub-selection" <?php if($subscription_request['payment_plan']){ ?> style="display:none"; <?php } ?> >
<section>
	<center>
		<div class="container cofsub-rost">
			<img class="img-responsive" src="<?php echo $this->getSkinUrl('images/sdas.png'); ?>" alt="banner">
		</div>
	</center>
</section>

<section>
	<center>
		<div class="container   cofsub-select_rost">
			<div class="heading">
				<h4 style="color:gray">SELECT YOUR ROAST PROFILE PREFERENCE</h4>
			</div>
			<div class="col-sm-12">
		<?php
$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','roast_level');
						$attr = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
						
						if ($attr->usesSource()) {
							$attributeOptions = $attr ->getSource()->getAllOptions(false);
							
								foreach ($attributeOptions as $option) {
									if($option['value'] !=""){ 
									 $_img = $this->helper('attributeimage')->getAttributeImage($option['value']);
									 $description = $this->helper('attributeimage')->getAttributeDescription($option['value']);
									 
									?>
									<div class="col-sm-3 ">
									
									<input class="roast_level" data-title="<?php echo $option['label'];?>" id="roast_level<?php echo $option['value']; ?>"  type="radio" name="roast_level" value="<?php echo $option['value']; ?>" <?php if($subscription_request['roast_level'] && $option['value'] == $subscription_request['roast_level']){ echo 'checked=checked'; } ?>/>
									<label for="roast_level<?php echo $option['value']; ?>">
										<?php if($_img!=""){ ?>
										<img class="img-responsive" src="<?php echo $_img; ?>"  />
									<?php } ?>
										<div class="sub_title"><?php echo $option['label'];?></div>
										</label>
										<p><?php echo $description; ?></p>
									</div>
									<?php
									}
								}
						}
					?>
			</div>	
		</div>
	</center>
</section>
<section class="coffee_type" <?php if($subscription_request['coffee_type']){ ?> style="display:block;" <?php }else{ ?> style="display:none;" <?php } ?>>
	<center>
		<div class="container cofsub-select_blend " >
			<div class="heading">
				<h4 style="color:gray">SELECT YOUR PREFERED BLEND</h4>
			</div>
			<div class="col-sm-12">
			<?php
$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','coffee_type');
						$attr = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
						
						if ($attr->usesSource()) {
							$attributeOptions = $attr ->getSource()->getAllOptions(false);
							
								foreach ($attributeOptions as $option) {
									if($option['value'] !=""){ 
									 $_img = $this->helper('attributeimage')->getAttributeImage($option['value']);
									 $description = $this->helper('attributeimage')->getAttributeDescription($option['value']);
									?>
									<div class="col-sm-4">
									
									<input data-title="<?php echo $option['label'];?>" class="coffee_type" id="coffee_type<?php echo $option['value']; ?>"  type="checkbox" name="coffee_type" value="<?php echo $option['value']; ?>" <?php if($subscription_request['coffee_type'] && $option['value'] == $subscription_request['coffee_type']){ echo 'checked=checked'; } ?>/>
									<label for="coffee_type<?php echo $option['value']; ?>"> 
										<?php if($_img!=""){ ?>
										<img class="img-responsive blend" src="<?php echo $_img; ?>" />
									<?php } ?>
										
										<div class="sub_title"><?php echo $option['label'];?></div>
										</label>
									<p><?php echo $description; ?></p>
									</div>
									<?php
									}
								}
						}
				?>
								
			</div>
			
		</div>
	</center>
</section>


<section class="how_often" <?php if($subscription_request['how_often']){ ?> style="display:block;" <?php }else{ ?> style="display:none;" <?php } ?>>
	<center>
		<div class="container   cofsub-select_shiping">
			<div class="heading">
				<h4 style="color:gray">SELECT YOUR SHIPING SCHEDULE</h4>
			</div>
			<div class="col-sm-12">
			<?php
$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','how_often');
						$attr = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
						
						if ($attr->usesSource()) {
							$attributeOptions = $attr ->getSource()->getAllOptions(false);
							
								foreach ($attributeOptions as $option) {
									if($option['value'] !=""){ 
									 $_img = $this->helper('attributeimage')->getAttributeImage($option['value']);
									 $description = $this->helper('attributeimage')->getAttributeDescription($option['value']);
									 $params = $this->helper('attributeimage')->getAttributeParams($option['value']);
									?>
									<div class="col-sm-3 circle-bg">
									
									<input data-title="<?php echo $option['label'];?>" class="coffee_weeks" data-weeks="<?php echo $params; ?>" id="how_often<?php echo $option['value']; ?>"  type="radio" name="how_often" value="<?php echo $option['value']; ?>" <?php if($subscription_request['how_often'] && $option['value'] == $subscription_request['how_often']){ echo 'checked=checked'; } ?>/>
									<label for="how_often<?php echo $option['value']; ?>">
									<?php if($_img!=""){ ?>
										<img class="img-responsive blend" src="<?php echo $_img; ?>"  />
									<?php } ?>
										<div class="sub_title"><?php echo $option['label'];?></div>
									</label>
									<p><?php echo $description; ?></p>
									</div>
									<?php
									}
								}
						}
				?>
								
			</div>	
			
		</div>
	</center>
</section>


<section class="which_tier" <?php if($subscription_request['tier_type']){ ?> style="display:block;" <?php }else{ ?> style="display:none;" <?php } ?>>
	<center>
		<div class="container   cofsub-select_payment">
			<div class="heading">
				<h4 style="color:gray">SELECT YOUR PAYMENT PLAN</h4>
			</div>
			<div class="col-sm-12">
			<?php
$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','tier_type');
						$attr = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
						
						if ($attr->usesSource()) {
							$attributeOptions = $attr ->getSource()->getAllOptions(false);
							
								foreach ($attributeOptions as $option) {
									if($option['value'] !=""){ 
									 $_img = $this->helper('attributeimage')->getAttributeImage($option['value']);
									 $description = $this->helper('attributeimage')->getAttributeDescription($option['value']);
									$params = $this->helper('attributeimage')->getAttributeParams($option['value']);
									?>
									<div class="col-sm-6">
									
									<input data-title="<?php echo $option['label'];?>" class="tier_price_sel" id="tier_type<?php echo $option['value']; ?>" data-priceselector="<?php echo $params; ?>"  type="radio" name="tier_type" value="<?php echo $option['value']; ?>" <?php if($subscription_request['tier_type'] && $option['value'] == $subscription_request['tier_type']){ echo 'checked=checked'; } ?>/>
									<label class="tier_type" for="tier_type<?php echo $option['value']; ?>">
										
										<img class="img-responsive" src="<?php echo $_img; ?>"  />
										<div class="sub_title"><?php echo $option['label'];?></div>
									</label>
									<p><?php echo $description; ?></p>
									</div>
									<?php
									}
								}
						}
								?>
								
			</div>
			
		</div>
	</center>
</section>
<section class="payment_plan" <?php if($subscription_request['payment_plan']){ ?> style="display:block;" <?php }else{ ?> style="display:none;" <?php } ?>>
	<center>
		<div class="container   cofsub-select_payment">
			<div class="heading">
				<h4 style="color:gray">SELECT YOUR PAYMENT PLAN</h4>
			</div>
			<div class="col-sm-12">
			<?php
$payment_plan = Mage::getModel('subscription/paymentplan')->getCollection();
$payment_plan->addFieldToFilter('status',array('eq'=>1));
$payment_plan->getSelect()->limit(3);


$default_base_price = Mage::getStoreConfig('subscription/subscription/basic');

$default_deluxe_price = Mage::getStoreConfig('subscription/subscription/deluxe');

							foreach($payment_plan as $payment){
							
									 $base_price = ($default_base_price * $payment->getPrice())/100;
									 $final_base_price = $default_base_price - $base_price;
									$deluxe_price = ($default_deluxe_price * $payment->getPrice())/100;
									 $final_delux_price = $default_deluxe_price - $deluxe_price;
									 $shipm_amnt_base = $final_base_price * $payment->getNoOfShip();
									 $shipm_amnt_delux = $final_delux_price * $payment->getNoOfShip();
									$total_ship_amount_delux = Mage::helper('core')->currency($shipm_amnt_delux, true, false);
									 ?>
									
									<div class="col-sm-4">
									
									<input data-baseamt="<?php echo $shipm_amnt_base; ?>" data-deluxamt="<?php echo $total_ship_amount_delux; ?>" data-title="<?php echo $payment->getName(); ?>" class="payment_plan_sel" id="payment_plan<?php echo $payment->getId(); ?>"  type="radio" name="payment_plan" value="<?php echo $payment->getId(); ?>" <?php if($subscription_request['payment_plan'] && $payment->getId() == $subscription_request['payment_plan']){ echo 'checked=checked'; } ?>/>
									<label for="payment_plan<?php echo $payment->getId(); ?>">
										<?php if($payment->getImage()!=""){ ?>
										<img class="img-responsive" src="<?php echo Mage::getBaseUrl('media').'blog/'.$payment->getImage(); ?>"  />
										<?php } ?>
										<div class="sub_title"><?php echo $payment->getName(); ?></div>
									</label>
									<div class="price_per_shipment">
									
									<span class="base_price_default price_cus_switcher" style="display:none;" >
										<?php echo Mage::helper('core')->currency($final_base_price, true, false); ?> / Shipment
										
									</span>
									<span class="delux_price_default price_cus_switcher" style="display:none;" >
									<?php echo Mage::helper('core')->currency($final_delux_price, true, false); ?> / Shipment
									<input type="hidden" name="total_delux_price" class="total_price_val" value="<?php echo $total_ship_amount_delux; ?>" />
									</span>
									
									</div>
									<?php if($payment->getPrice()> 0){ ?>
										<div class="save_percent"><?php echo 'Save '.$payment->getPrice().'%'; ?></div>
									<?php } ?>
									</div>
							<?php } ?>
								
							
		</div>
			
		</div>
	</center>
</section>
<section>
	<center>
		<div class="container   cofsub-btn">
			
			 <button id="custom_checkout" style="display:none;" type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Go to Checkout')) ?>" class="button"><span><span><?php echo $this->__('Go to Checkout') ?></span></span></button>
			
		</div>
	</center>
</section>
</div>

<!----------------------Html End------------------------------------->
							
	<?php
	
	$product_id = '11';
	$product = Mage::getModel('catalog/product')->load($product_id);
	$productMediaConfig = Mage::getModel('catalog/product_media_config');

$baseImageUrl  = $productMediaConfig->getMediaUrl($product->getImage());
$smallImageUrl = $productMediaConfig->getMediaUrl($product->getSmallImage());
$thumbnailUrl  = $productMediaConfig->getMediaUrl($product->getThumbnail());
?>

<div class="checkout-information col-sm-12" <?php if($subscription_request['payment_plan']){ ?> style="display:block"; <?php }else{ ?> style="display:none;" <?php } ?>>


	<div class="subscribe-info col-sm-6"> 
	<img src="<?php echo $baseImageUrl ?>" width="300" />
		<div class="left-checkout-section">
		<ul class="left-labelsection">
			<li>Roast</li>
			<li>Type</li>
			<li>Frequency</li>
			<li>Tier</li>
			<li>Price</li>
			<li>Payment Schedule</li>
			<li>Shipping</li>
		</ul>
		
			<ul class="right-valuesection">
				<li id="roast_val"><?php echo ($subscription_request['roast_hidden_val'])?$subscription_request['roast_hidden_val']:'N/A'; ?></li>
				<li id="type_val"><?php echo ($subscription_request['type_hidden_val'])?$subscription_request['type_hidden_val']:'N/A'; ?></li>
				<li id="frequency_val"><?php echo ($subscription_request['frequency_hidden_val'])?$subscription_request['frequency_hidden_val']:'N/A'; ?></li>
				<li id="tier_val"><?php echo ($subscription_request['tier_hidden_val'])?$subscription_request['tier_hidden_val']:'N/A'; ?></li>
				<li id="price_val"><?php echo ($subscription_request['total_delux_price'])?$subscription_request['total_delux_price']:'N/A'; ?></li>
				<?php if($subscription_request['paymentid_hidden_val']){ 
				$payment_plan = Mage::getModel('subscription/paymentplan')->load($subscription_request['paymentid_hidden_val']);
				$namee = $payment_plan->getName();
				 }else{ 
				 $namee = '';
				 }
				 ?>
				<li id="payment_schedule_val"><?php echo $name; ?></li>
				<li>Free</li>
			<input type="hidden" id="roast_hidden_val" name="roast_hidden_val" value="<?php echo ($subscription_request['roast_hidden_val'])?$subscription_request['roast_hidden_val']:''; ?>">	
			<input type="hidden" id="type_hidden_val" name="type_hidden_val" value="<?php echo ($subscription_request['type_hidden_val'])?$subscription_request['type_hidden_val']:''; ?>">	
			<input type="hidden" id="frequency_hidden_val" name="frequency_hidden_val" value="<?php echo ($subscription_request['frequency_hidden_val'])?$subscription_request['frequency_hidden_val']:''; ?>">	
			<input type="hidden" id="tier_hidden_val" name="tier_hidden_val" value="<?php echo ($subscription_request['tier_hidden_val'])?$subscription_request['tier_hidden_val']:''; ?>">	
			<input type="hidden" id="paymentid_hidden_val" name="paymentid_hidden_val" value="<?php echo $subscription_request['paymentid_hidden_val']; ?>">	
			<input type="hidden" id="tier_hd_hidden_val" name="tier_hd_hidden_val" value="<?php echo $subscription_request['tier_hd_hidden_val']; ?>" >	
				
		</ul>
		</div>
		
	</div>
		<div class="col-sm-6 right-checkout-section">
			<?php echo $this->getChildHtml('billing'); ?>
			<h2>Billing Information</h2>
			<?php $payment_method = $this->getActivPaymentMethods();
			
			?>
			<h2>Payment Method</h2>
			<?php foreach($payment_method as $method){ ?>
			<div class="col-sm-12">
				<input id="<?php echo $method['value']; ?>" type="radio"  name="payment_method" value="<?php echo $method['value']; ?>" >
					<label for="<?php echo $method['value']; ?>"><?php echo $method['label']; ?></label>
			</div>
			<?php } ?>
		</div>
		<div style="float:left">
		<span class="please-wait" id="custom-cart" style="display:none;float:left;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
		</div>
	 <button id="last_checkout" type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Checkout')) ?>" class="button"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
	 <button id="go_back"  type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Go Back')) ?>" class="button"><span><span><?php echo $this->__('Go Back') ?></span></span></button>

	
</div>
</form>
</div>
<?php
/*
    $cart = Mage::getModel('checkout/cart');
    $cart->init();


    $params = array(
        'product' => $product->getId(), // This would be $product->getId()
        'qty' => 1,
        'options' => array(
            2 => "Payment Schedule",
            3 => "Tier",
            4 => "Frequency",
            5 => "Type",
            6 => "Roast"
        )
    );      



    try {   
        $cart->addProduct($product, new Varien_Object($params));
        Mage::getSingleton('checkout/session')->setCartWasUpdated(true);
        $cart->save();
    }
    catch (Exception $ex) {
        echo $ex->getMessage();
    }*/
	?>
<script type="text/javascript">
 //< ![CDATA[
        var customForm = new VarienForm('sub_checkout');
		
var billingForm = new VarienForm("co-billing-form");
    //]]>
jQuery(document).ready(function(){
	
	jQuery('#billing-address-select').attr('onchange','');
	jQuery('#billing-address-select').change(function(){
		if(jQuery(this).val()== ''){
			jQuery('#billing-new-address-form').show();
		}
		else {
			jQuery('#billing-new-address-form').hide();
		}	
	});
	jQuery('#last_checkout').click(function(event){
		jQuery( "#sub_checkout" ).submit();
	});
	jQuery( "#sub_checkout" ).submit(function( event ) {
		jQuery('#custom-cart').show();
		event.preventDefault();
		var link = jQuery('#sub_checkout').attr('action');
		
		jQuery.ajax({
		  method: "POST",
		  url: link,
		  data:jQuery( "#sub_checkout" ).serialize()
		})
	  .done(function( msg ) {
		  jQuery('#custom-cart').hide();
			alert( "Data Saved: " + msg );
	  });
		
});
	jQuery('#custom_checkout').on("click",function(){
		
		jQuery('.coffee-sub-selection').hide();
		jQuery('.checkout-information').show();
		
		var roast_level_value = jQuery("input[name='roast_level']:checked").attr('data-title');
		var coffee_type_str = '';
		 jQuery('.coffee_type:checkbox:checked').each(function(i){
          coffee_type_str += jQuery(this).attr('data-title')+',';
        });
		
		var coffee_type_selected = coffee_type_str.substring(0,coffee_type_str.length - 1);
		var how_often_value = jQuery("input[name='how_often']:checked").attr('data-title');
		var tier_type_value = jQuery("input[name='tier_type']:checked").attr('data-title');
		var price_value_selector = jQuery("input[name='tier_type']:checked").attr('data-priceselector');
		var payment_plan_value = jQuery("input[name='payment_plan']:checked").attr('data-title');
		var payment_plan_id = jQuery("input[name='payment_plan']:checked").val();
		var payment_base_value = jQuery("input[name='payment_plan']:checked").attr('data-baseamt');
		var payment_deluxamt_value = jQuery("input[name='payment_plan']:checked").attr('data-deluxamt');
	
		if(price_value_selector == 'base_price_default'){
			jQuery('#price_val').html(payment_base_value);
			jQuery('#tier_hd_hidden_val').val('base_price_default');
		}else if(price_value_selector == 'delux_price_default'){
			jQuery('#price_val').html(payment_deluxamt_value);
			jQuery('#tier_hd_hidden_val').val('delux_price_default');
		}
		
		
		var price_va = jQuery('.'+price_value_selector).html();
		
		
		jQuery('#roast_val').html(roast_level_value);
		jQuery('#roast_hidden_val').val(roast_level_value);
		jQuery('#type_val').html(coffee_type_selected);
		jQuery('#type_hidden_val').val(coffee_type_selected);
		jQuery('#frequency_val').html(how_often_value);
		jQuery('#frequency_hidden_val').val(how_often_value);
		jQuery('#tier_val').html(tier_type_value);
		jQuery('#tier_hidden_val').val(tier_type_value);
		
		jQuery('#payment_schedule_val').html(payment_plan_value);
		jQuery('#paymentid_hidden_val').val(payment_plan_id);
		
		jQuery.ajax({
		  method: "POST",
		  url: '<?php echo $this->getUrl('coffee-subscription/index/coffeesubscription'); ?>',
		  data:jQuery( "#sub_checkout" ).serialize()
		})
	  .done(function( msg ) {
		  //jQuery('#custom-cart').hide();
		//alert( "Data Saved: " + msg );
	  });
				
				
	});
	jQuery('#go_back').on("click",function(){
		//jQuery(this).hide();
		jQuery('.coffee-sub-selection').show();
		jQuery('.checkout-information').hide();
	});
	
	jQuery(".roast_level").on("click",function(){
		if (jQuery("input[name='roast_level']").is(':checked')) {
				jQuery('.coffee_type').show();
		}

	});
	jQuery(".coffee_type").on("click",function(){
		jQuery('.how_often').show();

	});
	jQuery(".coffee_weeks").on("click",function(){
		jQuery('.which_tier').show();

	});
	jQuery(".tier_price_sel").on("click",function(){
		var price_selector = jQuery(this).data('priceselector');
		
		jQuery('.payment_plan').show();
		jQuery('.price_cus_switcher').hide();
		jQuery('.'+price_selector).show();
		//jQuery('#custom_checkout').show();
	});
	jQuery(".payment_plan_sel").on("click",function(){
		
		jQuery('#custom_checkout').show();
	});
	
	
	
});
</script>								