<div >
<section>
	<img class="img-responsive" src="<?php echo $this->getSkinUrl('images/banner.jpg'); ?>" alt="banner">
</section>


<div class="coffee-sub-selection">
<section>
	<center>
		<div class="container cofsub-rost">
			<img class="img-responsive" src="<?php echo $this->getSkinUrl('images/sdas.png'); ?>" alt="banner">
		</div>
	</center>
</section>
<section>
	<center>
		<div class="container   cofsub-select_rost">
			<div class="heading">
				<h4 style="color:gray">SELECT YOUR ROAST PROFILE PREFERENCE</h4>
			</div>
			<div class="col-sm-12">
		<?php
$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','roast_level');
						$attr = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
						
						if ($attr->usesSource()) {
							$attributeOptions = $attr ->getSource()->getAllOptions(false);
							
								foreach ($attributeOptions as $option) {
									if($option['value'] !=""){ 
									 $_img = $this->helper('attributeimage')->getAttributeImage($option['value']);
									 $description = $this->helper('attributeimage')->getAttributeDescription($option['value']);
									 
									?>
									<div class="col-sm-3 ">
									
									<input class="roast_level" data-title="<?php echo $option['label'];?>" id="roast_level<?php echo $option['value']; ?>"  type="radio" name="roast_level" value="<?php echo $option['value']; ?>"/>
									<label for="roast_level<?php echo $option['value']; ?>">
										<?php if($_img!=""){ ?>
										<img class="img-responsive" src="<?php echo $_img; ?>"  />
									<?php } ?>
										<div class="sub_title"><?php echo $option['label'];?></div>
										</label>
										<p><?php echo $description; ?></p>
									</div>
									<?php
									}
								}
						}
					?>
			</div>	
		</div>
	</center>
</section>
<section class="coffee_type" style="display:none;">
	<center>
		<div class="container cofsub-select_blend " >
			<div class="heading">
				<h4 style="color:gray">SELECT YOUR PREFERED BLEND</h4>
			</div>
			<div class="col-sm-12">
			<?php
$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','coffee_type');
						$attr = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
						
						if ($attr->usesSource()) {
							$attributeOptions = $attr ->getSource()->getAllOptions(false);
							
								foreach ($attributeOptions as $option) {
									if($option['value'] !=""){ 
									 $_img = $this->helper('attributeimage')->getAttributeImage($option['value']);
									 $description = $this->helper('attributeimage')->getAttributeDescription($option['value']);
									?>
									<div class="col-sm-3">
									
									<input data-title="<?php echo $option['label'];?>" class="coffee_type" id="coffee_type<?php echo $option['value']; ?>"  type="checkbox" name="coffee_type" value="<?php echo $option['value']; ?>"/>
									<label for="coffee_type<?php echo $option['value']; ?>"> 
										<?php if($_img!=""){ ?>
										<img class="img-responsive blend" src="<?php echo $_img; ?>" width="200" />
									<?php } ?>
										
										<div class="sub_title"><?php echo $option['label'];?></div>
										</label>
									<p><?php echo $description; ?></p>
									</div>
									<?php
									}
								}
						}
				?>
								
			</div>
			
		</div>
	</center>
</section>


<section class="how_often" style="display:none;">
	<center>
		<div class="container   cofsub-select_shiping">
			<div class="heading">
				<h4 style="color:gray">SELECT YOUR SHIPING SCHEDULE</h4>
			</div>
			<div class="col-sm-12">
			<?php
$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','how_often');
						$attr = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
						
						if ($attr->usesSource()) {
							$attributeOptions = $attr ->getSource()->getAllOptions(false);
							
								foreach ($attributeOptions as $option) {
									if($option['value'] !=""){ 
									 $_img = $this->helper('attributeimage')->getAttributeImage($option['value']);
									 $description = $this->helper('attributeimage')->getAttributeDescription($option['value']);
									 $params = $this->helper('attributeimage')->getAttributeParams($option['value']);
									?>
									<div class="col-sm-3 circle-bg">
									
									<input data-title="<?php echo $option['label'];?>" class="coffee_weeks" data-weeks="<?php echo $params; ?>" id="how_often<?php echo $option['value']; ?>"  type="radio" name="how_often" value="<?php echo $option['value']; ?>"/>
									<label for="how_often<?php echo $option['value']; ?>">
									<?php if($_img!=""){ ?>
										<img src="<?php echo $_img; ?>" width="200" />
									<?php } ?>
										<div class="sub_title"><?php echo $option['label'];?></div>
									</label>
									<p><?php echo $description; ?></p>
									</div>
									<?php
									}
								}
						}
				?>
								
			</div>	
			
		</div>
	</center>
</section>


<section class="which_tier" style="display:none;">
	<center>
		<div class="container   cofsub-select_payment">
			<div class="heading">
				<h4 style="color:gray">SELECT YOUR PAYMENT PLAN</h4>
			</div>
			<div class="col-sm-12">
			<?php
$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','tier_type');
						$attr = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
						
						if ($attr->usesSource()) {
							$attributeOptions = $attr ->getSource()->getAllOptions(false);
							
								foreach ($attributeOptions as $option) {
									if($option['value'] !=""){ 
									 $_img = $this->helper('attributeimage')->getAttributeImage($option['value']);
									 $description = $this->helper('attributeimage')->getAttributeDescription($option['value']);
									$params = $this->helper('attributeimage')->getAttributeParams($option['value']);
									?>
									<div class="col-sm-4">
									
									<input data-title="<?php echo $option['label'];?>" class="tier_price_sel" id="tier_type<?php echo $option['value']; ?>" data-priceselector="<?php echo $params; ?>"  type="radio" name="tier_type" value="<?php echo $option['value']; ?>"/>
									<label class="tier_type" for="tier_type<?php echo $option['value']; ?>">
										
										<img class="img-responsive" src="<?php echo $_img; ?>" width="200" />
										<div class="sub_title"><?php echo $option['label'];?></div>
									</label>
									<p><?php echo $description; ?></p>
									</div>
									<?php
									}
								}
						}
								?>
								
			</div>
			
		</div>
	</center>
</section>
<section class="payment_plan" style="display:none;">
	<center>
		<div class="container   cofsub-select_payment">
			<div class="heading">
				<h4 style="color:gray">SELECT YOUR PAYMENT PLAN</h4>
			</div>
			<div class="col-sm-12">
			<?php
$payment_plan = Mage::getModel('subscription/paymentplan')->getCollection();
$payment_plan->addFieldToFilter('status',array('eq'=>1));
$payment_plan->getSelect()->limit(3);


$default_base_price = Mage::getStoreConfig('subscription/subscription/basic');

$default_deluxe_price = Mage::getStoreConfig('subscription/subscription/deluxe');

							foreach($payment_plan as $payment){
							
									 $base_price = ($default_base_price * $payment->getPrice())/100;
									 $final_base_price = $default_base_price - $base_price;
									$deluxe_price = ($default_deluxe_price * $payment->getPrice())/100;
									 $final_delux_price = $default_deluxe_price - $deluxe_price;
									 $shipm_amnt_base = $final_base_price * $payment->getNoOfShip();
									 $shipm_amnt_delux = $final_delux_price * $payment->getNoOfShip();
									$total_ship_amount_delux = Mage::helper('core')->currency($shipm_amnt_delux, true, false);
									 ?>
									
									<div class="col-sm-4">
									
									<input data-baseamt="<?php echo $shipm_amnt_base; ?>" data-deluxamt="<?php echo $total_ship_amount_delux; ?>" data-title="<?php echo $payment->getName(); ?>" class="payment_plan_sel" id="payment_plan<?php echo $payment->getId(); ?>"  type="radio" name="payment_plan" value="<?php echo $payment->getId(); ?>"/>
									<label for="payment_plan<?php echo $payment->getId(); ?>">
										<?php if($payment->getImage()!=""){ ?>
										<img class="img-responsive" src="<?php echo Mage::getBaseUrl('media').'blog/'.$payment->getImage(); ?>" width="200" />
										<?php } ?>
										<div class="sub_title"><?php echo $payment->getName(); ?></div>
									</label>
									<div class="price_per_shipment">
									
									<span class="base_price_default price_cus_switcher" style="display:none;" >
										<?php echo Mage::helper('core')->currency($final_base_price, true, false); ?> / Shipment
										
									</span>
									<span class="delux_price_default price_cus_switcher" style="display:none;" >
									<?php echo Mage::helper('core')->currency($final_delux_price, true, false); ?> / Shipment
									<input type="hidden" name="total_delux_price" class="total_price_val" value="<?php echo $total_ship_amount_delux; ?>" />
									</span>
									
									</div>
									<?php if($payment->getPrice()> 0){ ?>
										<div class="save_percent"><?php echo 'Save '.$payment->getPrice().'%'; ?></div>
									<?php } ?>
									</div>
							<?php } ?>
								
							
		</div>
			
		</div>
	</center>
</section>
<section>
	<center>
		<div class="container   cofsub-btn">
			<h4 class="box"><input id="custom_checkout" style="display:none;" type="button" name="checkout" value="Go to Checkout"/></h4>
		</div>
	</center>
</section>
</div>
</div>
<?php


?>
<!----------------------Html End------------------------------------->
							
	<?php
	
	$product_id = '11';
	$product = Mage::getModel('catalog/product')->load($product_id);
	$productMediaConfig = Mage::getModel('catalog/product_media_config');

$baseImageUrl  = $productMediaConfig->getMediaUrl($product->getImage());
$smallImageUrl = $productMediaConfig->getMediaUrl($product->getSmallImage());
$thumbnailUrl  = $productMediaConfig->getMediaUrl($product->getThumbnail());
?>

<div class="checkout-information" style="display:none;">
<img src="<?php echo $baseImageUrl ?>" width="300" />
	<div class="subscribe-info">
		
		<ul class="left-labelsection">
			<li>Roast</li>
			<li>Type</li>
			<li>Frequency</li>
			<li>Tier</li>
			<li>Price</li>
			<li>Payment Schedule</li>
			<li>Shipping</li>
		</ul>
		
			<ul class="right-valuesection">
				<li id="roast_val">value</li>
				<li id="type_val">value</li>
				<li id="frequency_val">value</li>
				<li id="tier_val">value</li>
				<li id="price_val">value</li>
				<li id="payment_schedule_val">value</li>
				<li>Free</li>
		</ul>
	</div>
	<input id="last_checkout" type="button" name="checkout" value="Checkout"/>
	<input id="go_back" type="button" name="back" value="Go Back"/>
</div>
<?php
/*
    $cart = Mage::getModel('checkout/cart');
    $cart->init();


    $params = array(
        'product' => $product->getId(), // This would be $product->getId()
        'qty' => 1,
        'options' => array(
            2 => "Payment Schedule",
            3 => "Tier",
            4 => "Frequency",
            5 => "Type",
            6 => "Roast"
        )
    );      



    try {   
        $cart->addProduct($product, new Varien_Object($params));
        Mage::getSingleton('checkout/session')->setCartWasUpdated(true);
        $cart->save();
    }
    catch (Exception $ex) {
        echo $ex->getMessage();
    }*/
	?>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('#custom_checkout').on("click",function(){
		
		jQuery('.coffee-sub-selection').hide();
		jQuery('.checkout-information').show();
		
		var roast_level_value = jQuery("input[name='roast_level']:checked").attr('data-title');
		var coffee_type_str = '';
		 jQuery('.coffee_type:checkbox:checked').each(function(i){
          coffee_type_str += jQuery(this).attr('data-title')+',';
        });
		
		var coffee_type_selected = coffee_type_str.substring(0,coffee_type_str.length - 1);
		var how_often_value = jQuery("input[name='how_often']:checked").attr('data-title');
		var tier_type_value = jQuery("input[name='tier_type']:checked").attr('data-title');
		var price_value_selector = jQuery("input[name='tier_type']:checked").attr('data-priceselector');
		var payment_plan_value = jQuery("input[name='payment_plan']:checked").attr('data-title');
		var payment_base_value = jQuery("input[name='payment_plan']:checked").attr('data-baseamt');
		var payment_deluxamt_value = jQuery("input[name='payment_plan']:checked").attr('data-deluxamt');
	
		if(price_value_selector == 'base_price_default'){
			jQuery('#price_val').html(payment_base_value);
		}else if(price_value_selector == 'delux_price_default'){
			jQuery('#price_val').html(payment_deluxamt_value);
		}
		
		
		var price_va = jQuery('.'+price_value_selector).html();
		
		
		jQuery('#roast_val').html(roast_level_value);
		jQuery('#type_val').html(coffee_type_selected);
		jQuery('#frequency_val').html(how_often_value);
		jQuery('#tier_val').html(tier_type_value);
		
		jQuery('#payment_schedule_val').html(payment_plan_value);
				
				
	});
	jQuery('#go_back').on("click",function(){
		//jQuery(this).hide();
		jQuery('.coffee-sub-selection').show();
		jQuery('.checkout-information').hide();
	});
	
	jQuery(".roast_level").on("click",function(){
		if (jQuery("input[name='roast_level']").is(':checked')) {
				jQuery('.coffee_type').show();
		}

	});
	jQuery(".coffee_type").on("click",function(){
		jQuery('.how_often').show();

	});
	jQuery(".coffee_weeks").on("click",function(){
		jQuery('.which_tier').show();

	});
	jQuery(".tier_price_sel").on("click",function(){
		var price_selector = jQuery(this).data('priceselector');
		
		jQuery('.payment_plan').show();
		jQuery('.price_cus_switcher').hide();
		jQuery('.'+price_selector).show();
		//jQuery('#custom_checkout').show();
	});
	jQuery(".payment_plan_sel").on("click",function(){
		
		jQuery('#custom_checkout').show();
	});
	
	payment_plan
	
});
</script>								